/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nam_healthforyou_ImageUtils */

#ifndef _Included_com_example_nam_healthforyou_ImageUtils
#define _Included_com_example_nam_healthforyou_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nam_healthforyou_ImageUtils
 * Method:    convertYUV420SPToARGB8888
 * Signature: ([B[IIIZ)V
 */
JNIEXPORT void JNICALL Java_com_example_nam_healthforyou_ImageUtils_convertYUV420SPToARGB8888
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jint, jboolean);

/*
 * Class:     com_example_nam_healthforyou_ImageUtils
 * Method:    convertYUV420ToARGB8888
 * Signature: ([B[B[B[IIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_example_nam_healthforyou_ImageUtils_convertYUV420ToARGB8888
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jintArray, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_example_nam_healthforyou_ImageUtils
 * Method:    convertYUV420SPToRGB565
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_nam_healthforyou_ImageUtils_convertYUV420SPToRGB565
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_nam_healthforyou_ImageUtils
 * Method:    convertARGB8888ToYUV420SP
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_nam_healthforyou_ImageUtils_convertARGB8888ToYUV420SP
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_nam_healthforyou_ImageUtils
 * Method:    convertRGB565ToYUV420SP
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_example_nam_healthforyou_ImageUtils_convertRGB565ToYUV420SP
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
